#ifndef APPSCONSTANTS_H_INCLUDED
#define APPSCONSTANTS_H_INCLUDED

#define STUDENT_NAME_LEN        64
#define PROGRAM_NAME_LEN        32
#define MAIL_ID_LEN             64
#define ADMISSION_STATUS_LEN    16

#endif // APPSCONSTANTS_H_INCLUDED